k=int(input())
a=list(map(int,input().split()))[:k]
b=list(map(int,input().split()))[:k]
c=list(map(int,input().split()))[:k]
suma=sum(a)
sumb=sum(b)
sumc=sum(c)
la=len(a)
lb=len(b)
lc=len(c)
mida=suma/la
midb=sumb/lb
midc=sumc/lc
print(suma,mida)
print(sumb,midb)
print(sumc,midc)
print(a)
print(b)
print(c)
